title: Yuchao Wang
logo: /assets/img/portfolio.png
description: Cognitive Science Undergrad and Life-long Student.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
twitter_username: uchaaaaaow 
twitter: uchaaaaaow 
twitter: https://twitter.com/