title: Yuchao Wang
logo: /assets/img/portfolio.png
description: To become a therapist-scientist improving clinical neurorehabilitation with engineering tools
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
favicon: /assets/img/spiral.png
