title: Yuchao Wang
logo: /assets/img/portfolio.jpg
description: Research specialist @PennMedLCNS | Neurorehab and beauty | he/him
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
