title: Yuchao Wang
logo: /assets/img/portfolio.png
description: To become a clinician-neuroscientist investigating motor-cognitive processes with engineering tools to improve neurorehabilitation
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
favicon: /assets/img/spiral.png
