title: Yuchao Wang
logo: /assets/img/portfolio.png
description: Investigating motor-cognitive networks with engineering tools
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
favicon: /assets/img/spiral.png
