title: Yuchao Wang
logo: /assets/img/portfolio.jpg
description: neuroscience|physical therapy|engineering|he/him
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
favicon: /assets/img/spiral.png
